# Generated by Django 5.0.6 on 2024-11-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_profesor_delete_profesores'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='materias',
            field=models.ManyToManyField(related_name='profesores', to='mypage.materia'),
        ),
    ]
