# Generated by Django 5.0.6 on 2024-11-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_profesor_materias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='correo_Inst',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
